-- Request klasifikasi Attendance terapproval dengan detail aman per tanggal.
-- Aman dijalankan ulang; tidak mengubah saldo cuti/lembur dan tidak memigrasikan data lama.

CREATE TABLE IF NOT EXISTS attendance_classification_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(36) NOT NULL,
  employee_id BIGINT UNSIGNED NOT NULL,
  site_id BIGINT UNSIGNED NOT NULL,
  classification_type VARCHAR(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason VARCHAR(500) NOT NULL,
  attachment_file_id BIGINT UNSIGNED NULL,
  approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  requested_by BIGINT UNSIGNED NOT NULL,
  requested_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME(3) NULL,
  review_notes VARCHAR(500) NULL,
  cancelled_by BIGINT UNSIGNED NULL,
  cancelled_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_by BIGINT UNSIGNED NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_attendance_classification_requests_uid (uid),
  UNIQUE KEY uq_attendance_classification_attachment (attachment_file_id),
  KEY idx_attendance_classification_employee_dates (employee_id, start_date, end_date),
  KEY idx_attendance_classification_site_status (site_id, approval_status, requested_at),
  CONSTRAINT chk_attendance_classification_dates CHECK (end_date >= start_date),
  CONSTRAINT chk_attendance_classification_type CHECK (classification_type IN ('LEAVE', 'SICK', 'PERMISSION')),
  CONSTRAINT chk_attendance_classification_approval CHECK (approval_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
  CONSTRAINT fk_attendance_classification_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_classification_site FOREIGN KEY (site_id) REFERENCES sites(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_classification_attachment FOREIGN KEY (attachment_file_id) REFERENCES files(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_classification_requested_by FOREIGN KEY (requested_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_classification_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_attendance_classification_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_classification_details (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid CHAR(36) NOT NULL,
  request_id BIGINT UNSIGNED NOT NULL,
  employee_id BIGINT UNSIGNED NOT NULL,
  business_date DATE NOT NULL,
  shift_assignment_id BIGINT UNSIGNED NULL,
  attendance_record_id BIGINT UNSIGNED NULL,
  outcome VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  notes VARCHAR(500) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_by BIGINT UNSIGNED NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_attendance_classification_details_uid (uid),
  UNIQUE KEY uq_attendance_classification_request_date (request_id, business_date),
  KEY idx_attendance_classification_detail_employee_date (employee_id, business_date, outcome),
  KEY idx_attendance_classification_detail_attendance (attendance_record_id),
  CONSTRAINT chk_attendance_classification_outcome CHECK (outcome IN ('PENDING', 'APPLIED', 'SKIPPED_NON_WORKDAY')),
  CONSTRAINT fk_attendance_classification_detail_request FOREIGN KEY (request_id) REFERENCES attendance_classification_requests(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_attendance_classification_detail_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_classification_detail_shift_assignment FOREIGN KEY (shift_assignment_id) REFERENCES employee_shift_assignments(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_attendance_classification_detail_attendance FOREIGN KEY (attendance_record_id) REFERENCES attendance_records(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

