/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedProduksiTransaksiRouteImport } from './routes/_authenticated/produksi/transaksi'
import { Route as AuthenticatedProduksiTerminalSetoranRouteImport } from './routes/_authenticated/produksi/terminal-setoran'
import { Route as AuthenticatedProduksiTarifSiteRouteImport } from './routes/_authenticated/produksi/tarif-site'
import { Route as AuthenticatedProduksiRekapRouteImport } from './routes/_authenticated/produksi/rekap'
import { Route as AuthenticatedProduksiMasterPekerjaanRouteImport } from './routes/_authenticated/produksi/master-pekerjaan'
import { Route as AuthenticatedPayrollSlipGajiRouteImport } from './routes/_authenticated/payroll/slip-gaji'
import { Route as AuthenticatedPayrollSimulasiRouteImport } from './routes/_authenticated/payroll/simulasi'
import { Route as AuthenticatedPayrollRiwayatRouteImport } from './routes/_authenticated/payroll/riwayat'
import { Route as AuthenticatedPayrollPeriodeRouteImport } from './routes/_authenticated/payroll/periode'
import { Route as AuthenticatedPayrollApprovalClosingRouteImport } from './routes/_authenticated/payroll/approval-closing'
import { Route as AuthenticatedKaryawanTambahKaryawanRouteImport } from './routes/_authenticated/karyawan/tambah-karyawan'
import { Route as AuthenticatedKaryawanRiwayatMutasiRouteImport } from './routes/_authenticated/karyawan/riwayat-mutasi'
import { Route as AuthenticatedKaryawanPkwtDokumenRouteImport } from './routes/_authenticated/karyawan/pkwt-dokumen'
import { Route as AuthenticatedKaryawanPkwtRouteImport } from './routes/_authenticated/karyawan/pkwt'
import { Route as AuthenticatedKaryawanDokumenRouteImport } from './routes/_authenticated/karyawan/dokumen'
import { Route as AuthenticatedKaryawanDataKaryawanRouteImport } from './routes/_authenticated/karyawan/data-karyawan'
import { Route as AuthenticatedKaryawanCetakIdCardRouteImport } from './routes/_authenticated/karyawan/cetak-id-card'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAttendanceScanRouteImport } from './routes/_authenticated/attendance/scan'
import { Route as AuthenticatedAttendanceRekapRouteImport } from './routes/_authenticated/attendance/rekap'
import { Route as AuthenticatedAttendanceMonitoringHarianRouteImport } from './routes/_authenticated/attendance/monitoring-harian'
import { Route as AuthenticatedAttendanceMasterShiftRouteImport } from './routes/_authenticated/attendance/master-shift'
import { Route as AuthenticatedAttendanceKoreksiRouteImport } from './routes/_authenticated/attendance/koreksi'
import { Route as AuthenticatedAdministrasiUserHakAksesRouteImport } from './routes/_authenticated/administrasi/user-hak-akses'
import { Route as AuthenticatedAdministrasiTemplateDokumenRouteImport } from './routes/_authenticated/administrasi/template-dokumen'
import { Route as AuthenticatedAdministrasiPengaturanRouteImport } from './routes/_authenticated/administrasi/pengaturan'
import { Route as AuthenticatedAdministrasiMasterDataRouteImport } from './routes/_authenticated/administrasi/master-data'
import { Route as AuthenticatedAdministrasiAuditTrailRouteImport } from './routes/_authenticated/administrasi/audit-trail'
import { Route as AuthenticatedKaryawanUbahKaryawanEmployeeUidRouteImport } from './routes/_authenticated/karyawan/ubah-karyawan.$employeeUid'
import { Route as AuthenticatedKaryawanPkwtTambahRouteImport } from './routes/_authenticated/karyawan/pkwt.tambah'
import { Route as AuthenticatedKaryawanPkwtContractUidRouteImport } from './routes/_authenticated/karyawan/pkwt.$contractUid'
import { Route as AuthenticatedKaryawanDokumenTambahRouteImport } from './routes/_authenticated/karyawan/dokumen.tambah'
import { Route as AuthenticatedKaryawanDokumenDocumentUidRouteImport } from './routes/_authenticated/karyawan/dokumen.$documentUid'
import { Route as AuthenticatedKaryawanDataKaryawanEmployeeUidRouteImport } from './routes/_authenticated/karyawan/data-karyawan_.$employeeUid'
import { Route as AuthenticatedKaryawanDataKaryawanTambahRouteImport } from './routes/_authenticated/karyawan/data-karyawan.tambah'
import { Route as AuthenticatedKaryawanPkwtContractUidUbahRouteImport } from './routes/_authenticated/karyawan/pkwt.$contractUid.ubah'
import { Route as AuthenticatedKaryawanDokumenDocumentUidUbahRouteImport } from './routes/_authenticated/karyawan/dokumen.$documentUid.ubah'
import { Route as AuthenticatedKaryawanDataKaryawanEmployeeUidEditRouteImport } from './routes/_authenticated/karyawan/data-karyawan_.$employeeUid.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProduksiTransaksiRoute =
  AuthenticatedProduksiTransaksiRouteImport.update({
    id: '/produksi/transaksi',
    path: '/produksi/transaksi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProduksiTerminalSetoranRoute =
  AuthenticatedProduksiTerminalSetoranRouteImport.update({
    id: '/produksi/terminal-setoran',
    path: '/produksi/terminal-setoran',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProduksiTarifSiteRoute =
  AuthenticatedProduksiTarifSiteRouteImport.update({
    id: '/produksi/tarif-site',
    path: '/produksi/tarif-site',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProduksiRekapRoute =
  AuthenticatedProduksiRekapRouteImport.update({
    id: '/produksi/rekap',
    path: '/produksi/rekap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProduksiMasterPekerjaanRoute =
  AuthenticatedProduksiMasterPekerjaanRouteImport.update({
    id: '/produksi/master-pekerjaan',
    path: '/produksi/master-pekerjaan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollSlipGajiRoute =
  AuthenticatedPayrollSlipGajiRouteImport.update({
    id: '/payroll/slip-gaji',
    path: '/payroll/slip-gaji',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollSimulasiRoute =
  AuthenticatedPayrollSimulasiRouteImport.update({
    id: '/payroll/simulasi',
    path: '/payroll/simulasi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollRiwayatRoute =
  AuthenticatedPayrollRiwayatRouteImport.update({
    id: '/payroll/riwayat',
    path: '/payroll/riwayat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollPeriodeRoute =
  AuthenticatedPayrollPeriodeRouteImport.update({
    id: '/payroll/periode',
    path: '/payroll/periode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollApprovalClosingRoute =
  AuthenticatedPayrollApprovalClosingRouteImport.update({
    id: '/payroll/approval-closing',
    path: '/payroll/approval-closing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanTambahKaryawanRoute =
  AuthenticatedKaryawanTambahKaryawanRouteImport.update({
    id: '/karyawan/tambah-karyawan',
    path: '/karyawan/tambah-karyawan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanRiwayatMutasiRoute =
  AuthenticatedKaryawanRiwayatMutasiRouteImport.update({
    id: '/karyawan/riwayat-mutasi',
    path: '/karyawan/riwayat-mutasi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanPkwtDokumenRoute =
  AuthenticatedKaryawanPkwtDokumenRouteImport.update({
    id: '/karyawan/pkwt-dokumen',
    path: '/karyawan/pkwt-dokumen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanPkwtRoute =
  AuthenticatedKaryawanPkwtRouteImport.update({
    id: '/karyawan/pkwt',
    path: '/karyawan/pkwt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanDokumenRoute =
  AuthenticatedKaryawanDokumenRouteImport.update({
    id: '/karyawan/dokumen',
    path: '/karyawan/dokumen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanDataKaryawanRoute =
  AuthenticatedKaryawanDataKaryawanRouteImport.update({
    id: '/karyawan/data-karyawan',
    path: '/karyawan/data-karyawan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanCetakIdCardRoute =
  AuthenticatedKaryawanCetakIdCardRouteImport.update({
    id: '/karyawan/cetak-id-card',
    path: '/karyawan/cetak-id-card',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceScanRoute =
  AuthenticatedAttendanceScanRouteImport.update({
    id: '/attendance/scan',
    path: '/attendance/scan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRekapRoute =
  AuthenticatedAttendanceRekapRouteImport.update({
    id: '/attendance/rekap',
    path: '/attendance/rekap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceMonitoringHarianRoute =
  AuthenticatedAttendanceMonitoringHarianRouteImport.update({
    id: '/attendance/monitoring-harian',
    path: '/attendance/monitoring-harian',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceMasterShiftRoute =
  AuthenticatedAttendanceMasterShiftRouteImport.update({
    id: '/attendance/master-shift',
    path: '/attendance/master-shift',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceKoreksiRoute =
  AuthenticatedAttendanceKoreksiRouteImport.update({
    id: '/attendance/koreksi',
    path: '/attendance/koreksi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrasiUserHakAksesRoute =
  AuthenticatedAdministrasiUserHakAksesRouteImport.update({
    id: '/administrasi/user-hak-akses',
    path: '/administrasi/user-hak-akses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrasiTemplateDokumenRoute =
  AuthenticatedAdministrasiTemplateDokumenRouteImport.update({
    id: '/administrasi/template-dokumen',
    path: '/administrasi/template-dokumen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrasiPengaturanRoute =
  AuthenticatedAdministrasiPengaturanRouteImport.update({
    id: '/administrasi/pengaturan',
    path: '/administrasi/pengaturan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrasiMasterDataRoute =
  AuthenticatedAdministrasiMasterDataRouteImport.update({
    id: '/administrasi/master-data',
    path: '/administrasi/master-data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrasiAuditTrailRoute =
  AuthenticatedAdministrasiAuditTrailRouteImport.update({
    id: '/administrasi/audit-trail',
    path: '/administrasi/audit-trail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanUbahKaryawanEmployeeUidRoute =
  AuthenticatedKaryawanUbahKaryawanEmployeeUidRouteImport.update({
    id: '/karyawan/ubah-karyawan/$employeeUid',
    path: '/karyawan/ubah-karyawan/$employeeUid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanPkwtTambahRoute =
  AuthenticatedKaryawanPkwtTambahRouteImport.update({
    id: '/tambah',
    path: '/tambah',
    getParentRoute: () => AuthenticatedKaryawanPkwtRoute,
  } as any)
const AuthenticatedKaryawanPkwtContractUidRoute =
  AuthenticatedKaryawanPkwtContractUidRouteImport.update({
    id: '/$contractUid',
    path: '/$contractUid',
    getParentRoute: () => AuthenticatedKaryawanPkwtRoute,
  } as any)
const AuthenticatedKaryawanDokumenTambahRoute =
  AuthenticatedKaryawanDokumenTambahRouteImport.update({
    id: '/tambah',
    path: '/tambah',
    getParentRoute: () => AuthenticatedKaryawanDokumenRoute,
  } as any)
const AuthenticatedKaryawanDokumenDocumentUidRoute =
  AuthenticatedKaryawanDokumenDocumentUidRouteImport.update({
    id: '/$documentUid',
    path: '/$documentUid',
    getParentRoute: () => AuthenticatedKaryawanDokumenRoute,
  } as any)
const AuthenticatedKaryawanDataKaryawanEmployeeUidRoute =
  AuthenticatedKaryawanDataKaryawanEmployeeUidRouteImport.update({
    id: '/karyawan/data-karyawan_/$employeeUid',
    path: '/karyawan/data-karyawan/$employeeUid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKaryawanDataKaryawanTambahRoute =
  AuthenticatedKaryawanDataKaryawanTambahRouteImport.update({
    id: '/tambah',
    path: '/tambah',
    getParentRoute: () => AuthenticatedKaryawanDataKaryawanRoute,
  } as any)
const AuthenticatedKaryawanPkwtContractUidUbahRoute =
  AuthenticatedKaryawanPkwtContractUidUbahRouteImport.update({
    id: '/ubah',
    path: '/ubah',
    getParentRoute: () => AuthenticatedKaryawanPkwtContractUidRoute,
  } as any)
const AuthenticatedKaryawanDokumenDocumentUidUbahRoute =
  AuthenticatedKaryawanDokumenDocumentUidUbahRouteImport.update({
    id: '/ubah',
    path: '/ubah',
    getParentRoute: () => AuthenticatedKaryawanDokumenDocumentUidRoute,
  } as any)
const AuthenticatedKaryawanDataKaryawanEmployeeUidEditRoute =
  AuthenticatedKaryawanDataKaryawanEmployeeUidEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedKaryawanDataKaryawanEmployeeUidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/laporan': typeof AuthenticatedLaporanRoute
  '/administrasi/audit-trail': typeof AuthenticatedAdministrasiAuditTrailRoute
  '/administrasi/master-data': typeof AuthenticatedAdministrasiMasterDataRoute
  '/administrasi/pengaturan': typeof AuthenticatedAdministrasiPengaturanRoute
  '/administrasi/template-dokumen': typeof AuthenticatedAdministrasiTemplateDokumenRoute
  '/administrasi/user-hak-akses': typeof AuthenticatedAdministrasiUserHakAksesRoute
  '/attendance/koreksi': typeof AuthenticatedAttendanceKoreksiRoute
  '/attendance/master-shift': typeof AuthenticatedAttendanceMasterShiftRoute
  '/attendance/monitoring-harian': typeof AuthenticatedAttendanceMonitoringHarianRoute
  '/attendance/rekap': typeof AuthenticatedAttendanceRekapRoute
  '/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/karyawan/cetak-id-card': typeof AuthenticatedKaryawanCetakIdCardRoute
  '/karyawan/data-karyawan': typeof AuthenticatedKaryawanDataKaryawanRouteWithChildren
  '/karyawan/dokumen': typeof AuthenticatedKaryawanDokumenRouteWithChildren
  '/karyawan/pkwt': typeof AuthenticatedKaryawanPkwtRouteWithChildren
  '/karyawan/pkwt-dokumen': typeof AuthenticatedKaryawanPkwtDokumenRoute
  '/karyawan/riwayat-mutasi': typeof AuthenticatedKaryawanRiwayatMutasiRoute
  '/karyawan/tambah-karyawan': typeof AuthenticatedKaryawanTambahKaryawanRoute
  '/payroll/approval-closing': typeof AuthenticatedPayrollApprovalClosingRoute
  '/payroll/periode': typeof AuthenticatedPayrollPeriodeRoute
  '/payroll/riwayat': typeof AuthenticatedPayrollRiwayatRoute
  '/payroll/simulasi': typeof AuthenticatedPayrollSimulasiRoute
  '/payroll/slip-gaji': typeof AuthenticatedPayrollSlipGajiRoute
  '/produksi/master-pekerjaan': typeof AuthenticatedProduksiMasterPekerjaanRoute
  '/produksi/rekap': typeof AuthenticatedProduksiRekapRoute
  '/produksi/tarif-site': typeof AuthenticatedProduksiTarifSiteRoute
  '/produksi/terminal-setoran': typeof AuthenticatedProduksiTerminalSetoranRoute
  '/produksi/transaksi': typeof AuthenticatedProduksiTransaksiRoute
  '/karyawan/data-karyawan/tambah': typeof AuthenticatedKaryawanDataKaryawanTambahRoute
  '/karyawan/data-karyawan/$employeeUid': typeof AuthenticatedKaryawanDataKaryawanEmployeeUidRouteWithChildren
  '/karyawan/dokumen/$documentUid': typeof AuthenticatedKaryawanDokumenDocumentUidRouteWithChildren
  '/karyawan/dokumen/tambah': typeof AuthenticatedKaryawanDokumenTambahRoute
  '/karyawan/pkwt/$contractUid': typeof AuthenticatedKaryawanPkwtContractUidRouteWithChildren
  '/karyawan/pkwt/tambah': typeof AuthenticatedKaryawanPkwtTambahRoute
  '/karyawan/ubah-karyawan/$employeeUid': typeof AuthenticatedKaryawanUbahKaryawanEmployeeUidRoute
  '/karyawan/data-karyawan/$employeeUid/edit': typeof AuthenticatedKaryawanDataKaryawanEmployeeUidEditRoute
  '/karyawan/dokumen/$documentUid/ubah': typeof AuthenticatedKaryawanDokumenDocumentUidUbahRoute
  '/karyawan/pkwt/$contractUid/ubah': typeof AuthenticatedKaryawanPkwtContractUidUbahRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/laporan': typeof AuthenticatedLaporanRoute
  '/': typeof AuthenticatedIndexRoute
  '/administrasi/audit-trail': typeof AuthenticatedAdministrasiAuditTrailRoute
  '/administrasi/master-data': typeof AuthenticatedAdministrasiMasterDataRoute
  '/administrasi/pengaturan': typeof AuthenticatedAdministrasiPengaturanRoute
  '/administrasi/template-dokumen': typeof AuthenticatedAdministrasiTemplateDokumenRoute
  '/administrasi/user-hak-akses': typeof AuthenticatedAdministrasiUserHakAksesRoute
  '/attendance/koreksi': typeof AuthenticatedAttendanceKoreksiRoute
  '/attendance/master-shift': typeof AuthenticatedAttendanceMasterShiftRoute
  '/attendance/monitoring-harian': typeof AuthenticatedAttendanceMonitoringHarianRoute
  '/attendance/rekap': typeof AuthenticatedAttendanceRekapRoute
  '/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/karyawan/cetak-id-card': typeof AuthenticatedKaryawanCetakIdCardRoute
  '/karyawan/data-karyawan': typeof AuthenticatedKaryawanDataKaryawanRouteWithChildren
  '/karyawan/dokumen': typeof AuthenticatedKaryawanDokumenRouteWithChildren
  '/karyawan/pkwt': typeof AuthenticatedKaryawanPkwtRouteWithChildren
  '/karyawan/pkwt-dokumen': typeof AuthenticatedKaryawanPkwtDokumenRoute
  '/karyawan/riwayat-mutasi': typeof AuthenticatedKaryawanRiwayatMutasiRoute
  '/karyawan/tambah-karyawan': typeof AuthenticatedKaryawanTambahKaryawanRoute
  '/payroll/approval-closing': typeof AuthenticatedPayrollApprovalClosingRoute
  '/payroll/periode': typeof AuthenticatedPayrollPeriodeRoute
  '/payroll/riwayat': typeof AuthenticatedPayrollRiwayatRoute
  '/payroll/simulasi': typeof AuthenticatedPayrollSimulasiRoute
  '/payroll/slip-gaji': typeof AuthenticatedPayrollSlipGajiRoute
  '/produksi/master-pekerjaan': typeof AuthenticatedProduksiMasterPekerjaanRoute
  '/produksi/rekap': typeof AuthenticatedProduksiRekapRoute
  '/produksi/tarif-site': typeof AuthenticatedProduksiTarifSiteRoute
  '/produksi/terminal-setoran': typeof AuthenticatedProduksiTerminalSetoranRoute
  '/produksi/transaksi': typeof AuthenticatedProduksiTransaksiRoute
  '/karyawan/data-karyawan/tambah': typeof AuthenticatedKaryawanDataKaryawanTambahRoute
  '/karyawan/data-karyawan/$employeeUid': typeof AuthenticatedKaryawanDataKaryawanEmployeeUidRouteWithChildren
  '/karyawan/dokumen/$documentUid': typeof AuthenticatedKaryawanDokumenDocumentUidRouteWithChildren
  '/karyawan/dokumen/tambah': typeof AuthenticatedKaryawanDokumenTambahRoute
  '/karyawan/pkwt/$contractUid': typeof AuthenticatedKaryawanPkwtContractUidRouteWithChildren
  '/karyawan/pkwt/tambah': typeof AuthenticatedKaryawanPkwtTambahRoute
  '/karyawan/ubah-karyawan/$employeeUid': typeof AuthenticatedKaryawanUbahKaryawanEmployeeUidRoute
  '/karyawan/data-karyawan/$employeeUid/edit': typeof AuthenticatedKaryawanDataKaryawanEmployeeUidEditRoute
  '/karyawan/dokumen/$documentUid/ubah': typeof AuthenticatedKaryawanDokumenDocumentUidUbahRoute
  '/karyawan/pkwt/$contractUid/ubah': typeof AuthenticatedKaryawanPkwtContractUidUbahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/administrasi/audit-trail': typeof AuthenticatedAdministrasiAuditTrailRoute
  '/_authenticated/administrasi/master-data': typeof AuthenticatedAdministrasiMasterDataRoute
  '/_authenticated/administrasi/pengaturan': typeof AuthenticatedAdministrasiPengaturanRoute
  '/_authenticated/administrasi/template-dokumen': typeof AuthenticatedAdministrasiTemplateDokumenRoute
  '/_authenticated/administrasi/user-hak-akses': typeof AuthenticatedAdministrasiUserHakAksesRoute
  '/_authenticated/attendance/koreksi': typeof AuthenticatedAttendanceKoreksiRoute
  '/_authenticated/attendance/master-shift': typeof AuthenticatedAttendanceMasterShiftRoute
  '/_authenticated/attendance/monitoring-harian': typeof AuthenticatedAttendanceMonitoringHarianRoute
  '/_authenticated/attendance/rekap': typeof AuthenticatedAttendanceRekapRoute
  '/_authenticated/attendance/scan': typeof AuthenticatedAttendanceScanRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/karyawan/cetak-id-card': typeof AuthenticatedKaryawanCetakIdCardRoute
  '/_authenticated/karyawan/data-karyawan': typeof AuthenticatedKaryawanDataKaryawanRouteWithChildren
  '/_authenticated/karyawan/dokumen': typeof AuthenticatedKaryawanDokumenRouteWithChildren
  '/_authenticated/karyawan/pkwt': typeof AuthenticatedKaryawanPkwtRouteWithChildren
  '/_authenticated/karyawan/pkwt-dokumen': typeof AuthenticatedKaryawanPkwtDokumenRoute
  '/_authenticated/karyawan/riwayat-mutasi': typeof AuthenticatedKaryawanRiwayatMutasiRoute
  '/_authenticated/karyawan/tambah-karyawan': typeof AuthenticatedKaryawanTambahKaryawanRoute
  '/_authenticated/payroll/approval-closing': typeof AuthenticatedPayrollApprovalClosingRoute
  '/_authenticated/payroll/periode': typeof AuthenticatedPayrollPeriodeRoute
  '/_authenticated/payroll/riwayat': typeof AuthenticatedPayrollRiwayatRoute
  '/_authenticated/payroll/simulasi': typeof AuthenticatedPayrollSimulasiRoute
  '/_authenticated/payroll/slip-gaji': typeof AuthenticatedPayrollSlipGajiRoute
  '/_authenticated/produksi/master-pekerjaan': typeof AuthenticatedProduksiMasterPekerjaanRoute
  '/_authenticated/produksi/rekap': typeof AuthenticatedProduksiRekapRoute
  '/_authenticated/produksi/tarif-site': typeof AuthenticatedProduksiTarifSiteRoute
  '/_authenticated/produksi/terminal-setoran': typeof AuthenticatedProduksiTerminalSetoranRoute
  '/_authenticated/produksi/transaksi': typeof AuthenticatedProduksiTransaksiRoute
  '/_authenticated/karyawan/data-karyawan/tambah': typeof AuthenticatedKaryawanDataKaryawanTambahRoute
  '/_authenticated/karyawan/data-karyawan_/$employeeUid': typeof AuthenticatedKaryawanDataKaryawanEmployeeUidRouteWithChildren
  '/_authenticated/karyawan/dokumen/$documentUid': typeof AuthenticatedKaryawanDokumenDocumentUidRouteWithChildren
  '/_authenticated/karyawan/dokumen/tambah': typeof AuthenticatedKaryawanDokumenTambahRoute
  '/_authenticated/karyawan/pkwt/$contractUid': typeof AuthenticatedKaryawanPkwtContractUidRouteWithChildren
  '/_authenticated/karyawan/pkwt/tambah': typeof AuthenticatedKaryawanPkwtTambahRoute
  '/_authenticated/karyawan/ubah-karyawan/$employeeUid': typeof AuthenticatedKaryawanUbahKaryawanEmployeeUidRoute
  '/_authenticated/karyawan/data-karyawan_/$employeeUid/edit': typeof AuthenticatedKaryawanDataKaryawanEmployeeUidEditRoute
  '/_authenticated/karyawan/dokumen/$documentUid/ubah': typeof AuthenticatedKaryawanDokumenDocumentUidUbahRoute
  '/_authenticated/karyawan/pkwt/$contractUid/ubah': typeof AuthenticatedKaryawanPkwtContractUidUbahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/laporan'
    | '/administrasi/audit-trail'
    | '/administrasi/master-data'
    | '/administrasi/pengaturan'
    | '/administrasi/template-dokumen'
    | '/administrasi/user-hak-akses'
    | '/attendance/koreksi'
    | '/attendance/master-shift'
    | '/attendance/monitoring-harian'
    | '/attendance/rekap'
    | '/attendance/scan'
    | '/errors/$error'
    | '/karyawan/cetak-id-card'
    | '/karyawan/data-karyawan'
    | '/karyawan/dokumen'
    | '/karyawan/pkwt'
    | '/karyawan/pkwt-dokumen'
    | '/karyawan/riwayat-mutasi'
    | '/karyawan/tambah-karyawan'
    | '/payroll/approval-closing'
    | '/payroll/periode'
    | '/payroll/riwayat'
    | '/payroll/simulasi'
    | '/payroll/slip-gaji'
    | '/produksi/master-pekerjaan'
    | '/produksi/rekap'
    | '/produksi/tarif-site'
    | '/produksi/terminal-setoran'
    | '/produksi/transaksi'
    | '/karyawan/data-karyawan/tambah'
    | '/karyawan/data-karyawan/$employeeUid'
    | '/karyawan/dokumen/$documentUid'
    | '/karyawan/dokumen/tambah'
    | '/karyawan/pkwt/$contractUid'
    | '/karyawan/pkwt/tambah'
    | '/karyawan/ubah-karyawan/$employeeUid'
    | '/karyawan/data-karyawan/$employeeUid/edit'
    | '/karyawan/dokumen/$documentUid/ubah'
    | '/karyawan/pkwt/$contractUid/ubah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/laporan'
    | '/'
    | '/administrasi/audit-trail'
    | '/administrasi/master-data'
    | '/administrasi/pengaturan'
    | '/administrasi/template-dokumen'
    | '/administrasi/user-hak-akses'
    | '/attendance/koreksi'
    | '/attendance/master-shift'
    | '/attendance/monitoring-harian'
    | '/attendance/rekap'
    | '/attendance/scan'
    | '/errors/$error'
    | '/karyawan/cetak-id-card'
    | '/karyawan/data-karyawan'
    | '/karyawan/dokumen'
    | '/karyawan/pkwt'
    | '/karyawan/pkwt-dokumen'
    | '/karyawan/riwayat-mutasi'
    | '/karyawan/tambah-karyawan'
    | '/payroll/approval-closing'
    | '/payroll/periode'
    | '/payroll/riwayat'
    | '/payroll/simulasi'
    | '/payroll/slip-gaji'
    | '/produksi/master-pekerjaan'
    | '/produksi/rekap'
    | '/produksi/tarif-site'
    | '/produksi/terminal-setoran'
    | '/produksi/transaksi'
    | '/karyawan/data-karyawan/tambah'
    | '/karyawan/data-karyawan/$employeeUid'
    | '/karyawan/dokumen/$documentUid'
    | '/karyawan/dokumen/tambah'
    | '/karyawan/pkwt/$contractUid'
    | '/karyawan/pkwt/tambah'
    | '/karyawan/ubah-karyawan/$employeeUid'
    | '/karyawan/data-karyawan/$employeeUid/edit'
    | '/karyawan/dokumen/$documentUid/ubah'
    | '/karyawan/pkwt/$contractUid/ubah'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/laporan'
    | '/_authenticated/'
    | '/_authenticated/administrasi/audit-trail'
    | '/_authenticated/administrasi/master-data'
    | '/_authenticated/administrasi/pengaturan'
    | '/_authenticated/administrasi/template-dokumen'
    | '/_authenticated/administrasi/user-hak-akses'
    | '/_authenticated/attendance/koreksi'
    | '/_authenticated/attendance/master-shift'
    | '/_authenticated/attendance/monitoring-harian'
    | '/_authenticated/attendance/rekap'
    | '/_authenticated/attendance/scan'
    | '/_authenticated/errors/$error'
    | '/_authenticated/karyawan/cetak-id-card'
    | '/_authenticated/karyawan/data-karyawan'
    | '/_authenticated/karyawan/dokumen'
    | '/_authenticated/karyawan/pkwt'
    | '/_authenticated/karyawan/pkwt-dokumen'
    | '/_authenticated/karyawan/riwayat-mutasi'
    | '/_authenticated/karyawan/tambah-karyawan'
    | '/_authenticated/payroll/approval-closing'
    | '/_authenticated/payroll/periode'
    | '/_authenticated/payroll/riwayat'
    | '/_authenticated/payroll/simulasi'
    | '/_authenticated/payroll/slip-gaji'
    | '/_authenticated/produksi/master-pekerjaan'
    | '/_authenticated/produksi/rekap'
    | '/_authenticated/produksi/tarif-site'
    | '/_authenticated/produksi/terminal-setoran'
    | '/_authenticated/produksi/transaksi'
    | '/_authenticated/karyawan/data-karyawan/tambah'
    | '/_authenticated/karyawan/data-karyawan_/$employeeUid'
    | '/_authenticated/karyawan/dokumen/$documentUid'
    | '/_authenticated/karyawan/dokumen/tambah'
    | '/_authenticated/karyawan/pkwt/$contractUid'
    | '/_authenticated/karyawan/pkwt/tambah'
    | '/_authenticated/karyawan/ubah-karyawan/$employeeUid'
    | '/_authenticated/karyawan/data-karyawan_/$employeeUid/edit'
    | '/_authenticated/karyawan/dokumen/$documentUid/ubah'
    | '/_authenticated/karyawan/pkwt/$contractUid/ubah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produksi/transaksi': {
      id: '/_authenticated/produksi/transaksi'
      path: '/produksi/transaksi'
      fullPath: '/produksi/transaksi'
      preLoaderRoute: typeof AuthenticatedProduksiTransaksiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produksi/terminal-setoran': {
      id: '/_authenticated/produksi/terminal-setoran'
      path: '/produksi/terminal-setoran'
      fullPath: '/produksi/terminal-setoran'
      preLoaderRoute: typeof AuthenticatedProduksiTerminalSetoranRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produksi/tarif-site': {
      id: '/_authenticated/produksi/tarif-site'
      path: '/produksi/tarif-site'
      fullPath: '/produksi/tarif-site'
      preLoaderRoute: typeof AuthenticatedProduksiTarifSiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produksi/rekap': {
      id: '/_authenticated/produksi/rekap'
      path: '/produksi/rekap'
      fullPath: '/produksi/rekap'
      preLoaderRoute: typeof AuthenticatedProduksiRekapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produksi/master-pekerjaan': {
      id: '/_authenticated/produksi/master-pekerjaan'
      path: '/produksi/master-pekerjaan'
      fullPath: '/produksi/master-pekerjaan'
      preLoaderRoute: typeof AuthenticatedProduksiMasterPekerjaanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/slip-gaji': {
      id: '/_authenticated/payroll/slip-gaji'
      path: '/payroll/slip-gaji'
      fullPath: '/payroll/slip-gaji'
      preLoaderRoute: typeof AuthenticatedPayrollSlipGajiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/simulasi': {
      id: '/_authenticated/payroll/simulasi'
      path: '/payroll/simulasi'
      fullPath: '/payroll/simulasi'
      preLoaderRoute: typeof AuthenticatedPayrollSimulasiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/riwayat': {
      id: '/_authenticated/payroll/riwayat'
      path: '/payroll/riwayat'
      fullPath: '/payroll/riwayat'
      preLoaderRoute: typeof AuthenticatedPayrollRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/periode': {
      id: '/_authenticated/payroll/periode'
      path: '/payroll/periode'
      fullPath: '/payroll/periode'
      preLoaderRoute: typeof AuthenticatedPayrollPeriodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll/approval-closing': {
      id: '/_authenticated/payroll/approval-closing'
      path: '/payroll/approval-closing'
      fullPath: '/payroll/approval-closing'
      preLoaderRoute: typeof AuthenticatedPayrollApprovalClosingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/tambah-karyawan': {
      id: '/_authenticated/karyawan/tambah-karyawan'
      path: '/karyawan/tambah-karyawan'
      fullPath: '/karyawan/tambah-karyawan'
      preLoaderRoute: typeof AuthenticatedKaryawanTambahKaryawanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/riwayat-mutasi': {
      id: '/_authenticated/karyawan/riwayat-mutasi'
      path: '/karyawan/riwayat-mutasi'
      fullPath: '/karyawan/riwayat-mutasi'
      preLoaderRoute: typeof AuthenticatedKaryawanRiwayatMutasiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/pkwt-dokumen': {
      id: '/_authenticated/karyawan/pkwt-dokumen'
      path: '/karyawan/pkwt-dokumen'
      fullPath: '/karyawan/pkwt-dokumen'
      preLoaderRoute: typeof AuthenticatedKaryawanPkwtDokumenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/pkwt': {
      id: '/_authenticated/karyawan/pkwt'
      path: '/karyawan/pkwt'
      fullPath: '/karyawan/pkwt'
      preLoaderRoute: typeof AuthenticatedKaryawanPkwtRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/dokumen': {
      id: '/_authenticated/karyawan/dokumen'
      path: '/karyawan/dokumen'
      fullPath: '/karyawan/dokumen'
      preLoaderRoute: typeof AuthenticatedKaryawanDokumenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/data-karyawan': {
      id: '/_authenticated/karyawan/data-karyawan'
      path: '/karyawan/data-karyawan'
      fullPath: '/karyawan/data-karyawan'
      preLoaderRoute: typeof AuthenticatedKaryawanDataKaryawanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/cetak-id-card': {
      id: '/_authenticated/karyawan/cetak-id-card'
      path: '/karyawan/cetak-id-card'
      fullPath: '/karyawan/cetak-id-card'
      preLoaderRoute: typeof AuthenticatedKaryawanCetakIdCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/scan': {
      id: '/_authenticated/attendance/scan'
      path: '/attendance/scan'
      fullPath: '/attendance/scan'
      preLoaderRoute: typeof AuthenticatedAttendanceScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/rekap': {
      id: '/_authenticated/attendance/rekap'
      path: '/attendance/rekap'
      fullPath: '/attendance/rekap'
      preLoaderRoute: typeof AuthenticatedAttendanceRekapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/monitoring-harian': {
      id: '/_authenticated/attendance/monitoring-harian'
      path: '/attendance/monitoring-harian'
      fullPath: '/attendance/monitoring-harian'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringHarianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/master-shift': {
      id: '/_authenticated/attendance/master-shift'
      path: '/attendance/master-shift'
      fullPath: '/attendance/master-shift'
      preLoaderRoute: typeof AuthenticatedAttendanceMasterShiftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/koreksi': {
      id: '/_authenticated/attendance/koreksi'
      path: '/attendance/koreksi'
      fullPath: '/attendance/koreksi'
      preLoaderRoute: typeof AuthenticatedAttendanceKoreksiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administrasi/user-hak-akses': {
      id: '/_authenticated/administrasi/user-hak-akses'
      path: '/administrasi/user-hak-akses'
      fullPath: '/administrasi/user-hak-akses'
      preLoaderRoute: typeof AuthenticatedAdministrasiUserHakAksesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administrasi/template-dokumen': {
      id: '/_authenticated/administrasi/template-dokumen'
      path: '/administrasi/template-dokumen'
      fullPath: '/administrasi/template-dokumen'
      preLoaderRoute: typeof AuthenticatedAdministrasiTemplateDokumenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administrasi/pengaturan': {
      id: '/_authenticated/administrasi/pengaturan'
      path: '/administrasi/pengaturan'
      fullPath: '/administrasi/pengaturan'
      preLoaderRoute: typeof AuthenticatedAdministrasiPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administrasi/master-data': {
      id: '/_authenticated/administrasi/master-data'
      path: '/administrasi/master-data'
      fullPath: '/administrasi/master-data'
      preLoaderRoute: typeof AuthenticatedAdministrasiMasterDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administrasi/audit-trail': {
      id: '/_authenticated/administrasi/audit-trail'
      path: '/administrasi/audit-trail'
      fullPath: '/administrasi/audit-trail'
      preLoaderRoute: typeof AuthenticatedAdministrasiAuditTrailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/ubah-karyawan/$employeeUid': {
      id: '/_authenticated/karyawan/ubah-karyawan/$employeeUid'
      path: '/karyawan/ubah-karyawan/$employeeUid'
      fullPath: '/karyawan/ubah-karyawan/$employeeUid'
      preLoaderRoute: typeof AuthenticatedKaryawanUbahKaryawanEmployeeUidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/pkwt/tambah': {
      id: '/_authenticated/karyawan/pkwt/tambah'
      path: '/tambah'
      fullPath: '/karyawan/pkwt/tambah'
      preLoaderRoute: typeof AuthenticatedKaryawanPkwtTambahRouteImport
      parentRoute: typeof AuthenticatedKaryawanPkwtRoute
    }
    '/_authenticated/karyawan/pkwt/$contractUid': {
      id: '/_authenticated/karyawan/pkwt/$contractUid'
      path: '/$contractUid'
      fullPath: '/karyawan/pkwt/$contractUid'
      preLoaderRoute: typeof AuthenticatedKaryawanPkwtContractUidRouteImport
      parentRoute: typeof AuthenticatedKaryawanPkwtRoute
    }
    '/_authenticated/karyawan/dokumen/tambah': {
      id: '/_authenticated/karyawan/dokumen/tambah'
      path: '/tambah'
      fullPath: '/karyawan/dokumen/tambah'
      preLoaderRoute: typeof AuthenticatedKaryawanDokumenTambahRouteImport
      parentRoute: typeof AuthenticatedKaryawanDokumenRoute
    }
    '/_authenticated/karyawan/dokumen/$documentUid': {
      id: '/_authenticated/karyawan/dokumen/$documentUid'
      path: '/$documentUid'
      fullPath: '/karyawan/dokumen/$documentUid'
      preLoaderRoute: typeof AuthenticatedKaryawanDokumenDocumentUidRouteImport
      parentRoute: typeof AuthenticatedKaryawanDokumenRoute
    }
    '/_authenticated/karyawan/data-karyawan_/$employeeUid': {
      id: '/_authenticated/karyawan/data-karyawan_/$employeeUid'
      path: '/karyawan/data-karyawan/$employeeUid'
      fullPath: '/karyawan/data-karyawan/$employeeUid'
      preLoaderRoute: typeof AuthenticatedKaryawanDataKaryawanEmployeeUidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan/data-karyawan/tambah': {
      id: '/_authenticated/karyawan/data-karyawan/tambah'
      path: '/tambah'
      fullPath: '/karyawan/data-karyawan/tambah'
      preLoaderRoute: typeof AuthenticatedKaryawanDataKaryawanTambahRouteImport
      parentRoute: typeof AuthenticatedKaryawanDataKaryawanRoute
    }
    '/_authenticated/karyawan/pkwt/$contractUid/ubah': {
      id: '/_authenticated/karyawan/pkwt/$contractUid/ubah'
      path: '/ubah'
      fullPath: '/karyawan/pkwt/$contractUid/ubah'
      preLoaderRoute: typeof AuthenticatedKaryawanPkwtContractUidUbahRouteImport
      parentRoute: typeof AuthenticatedKaryawanPkwtContractUidRoute
    }
    '/_authenticated/karyawan/dokumen/$documentUid/ubah': {
      id: '/_authenticated/karyawan/dokumen/$documentUid/ubah'
      path: '/ubah'
      fullPath: '/karyawan/dokumen/$documentUid/ubah'
      preLoaderRoute: typeof AuthenticatedKaryawanDokumenDocumentUidUbahRouteImport
      parentRoute: typeof AuthenticatedKaryawanDokumenDocumentUidRoute
    }
    '/_authenticated/karyawan/data-karyawan_/$employeeUid/edit': {
      id: '/_authenticated/karyawan/data-karyawan_/$employeeUid/edit'
      path: '/edit'
      fullPath: '/karyawan/data-karyawan/$employeeUid/edit'
      preLoaderRoute: typeof AuthenticatedKaryawanDataKaryawanEmployeeUidEditRouteImport
      parentRoute: typeof AuthenticatedKaryawanDataKaryawanEmployeeUidRoute
    }
  }
}

interface AuthenticatedKaryawanDataKaryawanRouteChildren {
  AuthenticatedKaryawanDataKaryawanTambahRoute: typeof AuthenticatedKaryawanDataKaryawanTambahRoute
}

const AuthenticatedKaryawanDataKaryawanRouteChildren: AuthenticatedKaryawanDataKaryawanRouteChildren =
  {
    AuthenticatedKaryawanDataKaryawanTambahRoute:
      AuthenticatedKaryawanDataKaryawanTambahRoute,
  }

const AuthenticatedKaryawanDataKaryawanRouteWithChildren =
  AuthenticatedKaryawanDataKaryawanRoute._addFileChildren(
    AuthenticatedKaryawanDataKaryawanRouteChildren,
  )

interface AuthenticatedKaryawanDokumenDocumentUidRouteChildren {
  AuthenticatedKaryawanDokumenDocumentUidUbahRoute: typeof AuthenticatedKaryawanDokumenDocumentUidUbahRoute
}

const AuthenticatedKaryawanDokumenDocumentUidRouteChildren: AuthenticatedKaryawanDokumenDocumentUidRouteChildren =
  {
    AuthenticatedKaryawanDokumenDocumentUidUbahRoute:
      AuthenticatedKaryawanDokumenDocumentUidUbahRoute,
  }

const AuthenticatedKaryawanDokumenDocumentUidRouteWithChildren =
  AuthenticatedKaryawanDokumenDocumentUidRoute._addFileChildren(
    AuthenticatedKaryawanDokumenDocumentUidRouteChildren,
  )

interface AuthenticatedKaryawanDokumenRouteChildren {
  AuthenticatedKaryawanDokumenDocumentUidRoute: typeof AuthenticatedKaryawanDokumenDocumentUidRouteWithChildren
  AuthenticatedKaryawanDokumenTambahRoute: typeof AuthenticatedKaryawanDokumenTambahRoute
}

const AuthenticatedKaryawanDokumenRouteChildren: AuthenticatedKaryawanDokumenRouteChildren =
  {
    AuthenticatedKaryawanDokumenDocumentUidRoute:
      AuthenticatedKaryawanDokumenDocumentUidRouteWithChildren,
    AuthenticatedKaryawanDokumenTambahRoute:
      AuthenticatedKaryawanDokumenTambahRoute,
  }

const AuthenticatedKaryawanDokumenRouteWithChildren =
  AuthenticatedKaryawanDokumenRoute._addFileChildren(
    AuthenticatedKaryawanDokumenRouteChildren,
  )

interface AuthenticatedKaryawanPkwtContractUidRouteChildren {
  AuthenticatedKaryawanPkwtContractUidUbahRoute: typeof AuthenticatedKaryawanPkwtContractUidUbahRoute
}

const AuthenticatedKaryawanPkwtContractUidRouteChildren: AuthenticatedKaryawanPkwtContractUidRouteChildren =
  {
    AuthenticatedKaryawanPkwtContractUidUbahRoute:
      AuthenticatedKaryawanPkwtContractUidUbahRoute,
  }

const AuthenticatedKaryawanPkwtContractUidRouteWithChildren =
  AuthenticatedKaryawanPkwtContractUidRoute._addFileChildren(
    AuthenticatedKaryawanPkwtContractUidRouteChildren,
  )

interface AuthenticatedKaryawanPkwtRouteChildren {
  AuthenticatedKaryawanPkwtContractUidRoute: typeof AuthenticatedKaryawanPkwtContractUidRouteWithChildren
  AuthenticatedKaryawanPkwtTambahRoute: typeof AuthenticatedKaryawanPkwtTambahRoute
}

const AuthenticatedKaryawanPkwtRouteChildren: AuthenticatedKaryawanPkwtRouteChildren =
  {
    AuthenticatedKaryawanPkwtContractUidRoute:
      AuthenticatedKaryawanPkwtContractUidRouteWithChildren,
    AuthenticatedKaryawanPkwtTambahRoute: AuthenticatedKaryawanPkwtTambahRoute,
  }

const AuthenticatedKaryawanPkwtRouteWithChildren =
  AuthenticatedKaryawanPkwtRoute._addFileChildren(
    AuthenticatedKaryawanPkwtRouteChildren,
  )

interface AuthenticatedKaryawanDataKaryawanEmployeeUidRouteChildren {
  AuthenticatedKaryawanDataKaryawanEmployeeUidEditRoute: typeof AuthenticatedKaryawanDataKaryawanEmployeeUidEditRoute
}

const AuthenticatedKaryawanDataKaryawanEmployeeUidRouteChildren: AuthenticatedKaryawanDataKaryawanEmployeeUidRouteChildren =
  {
    AuthenticatedKaryawanDataKaryawanEmployeeUidEditRoute:
      AuthenticatedKaryawanDataKaryawanEmployeeUidEditRoute,
  }

const AuthenticatedKaryawanDataKaryawanEmployeeUidRouteWithChildren =
  AuthenticatedKaryawanDataKaryawanEmployeeUidRoute._addFileChildren(
    AuthenticatedKaryawanDataKaryawanEmployeeUidRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdministrasiAuditTrailRoute: typeof AuthenticatedAdministrasiAuditTrailRoute
  AuthenticatedAdministrasiMasterDataRoute: typeof AuthenticatedAdministrasiMasterDataRoute
  AuthenticatedAdministrasiPengaturanRoute: typeof AuthenticatedAdministrasiPengaturanRoute
  AuthenticatedAdministrasiTemplateDokumenRoute: typeof AuthenticatedAdministrasiTemplateDokumenRoute
  AuthenticatedAdministrasiUserHakAksesRoute: typeof AuthenticatedAdministrasiUserHakAksesRoute
  AuthenticatedAttendanceKoreksiRoute: typeof AuthenticatedAttendanceKoreksiRoute
  AuthenticatedAttendanceMasterShiftRoute: typeof AuthenticatedAttendanceMasterShiftRoute
  AuthenticatedAttendanceMonitoringHarianRoute: typeof AuthenticatedAttendanceMonitoringHarianRoute
  AuthenticatedAttendanceRekapRoute: typeof AuthenticatedAttendanceRekapRoute
  AuthenticatedAttendanceScanRoute: typeof AuthenticatedAttendanceScanRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedKaryawanCetakIdCardRoute: typeof AuthenticatedKaryawanCetakIdCardRoute
  AuthenticatedKaryawanDataKaryawanRoute: typeof AuthenticatedKaryawanDataKaryawanRouteWithChildren
  AuthenticatedKaryawanDokumenRoute: typeof AuthenticatedKaryawanDokumenRouteWithChildren
  AuthenticatedKaryawanPkwtRoute: typeof AuthenticatedKaryawanPkwtRouteWithChildren
  AuthenticatedKaryawanPkwtDokumenRoute: typeof AuthenticatedKaryawanPkwtDokumenRoute
  AuthenticatedKaryawanRiwayatMutasiRoute: typeof AuthenticatedKaryawanRiwayatMutasiRoute
  AuthenticatedKaryawanTambahKaryawanRoute: typeof AuthenticatedKaryawanTambahKaryawanRoute
  AuthenticatedPayrollApprovalClosingRoute: typeof AuthenticatedPayrollApprovalClosingRoute
  AuthenticatedPayrollPeriodeRoute: typeof AuthenticatedPayrollPeriodeRoute
  AuthenticatedPayrollRiwayatRoute: typeof AuthenticatedPayrollRiwayatRoute
  AuthenticatedPayrollSimulasiRoute: typeof AuthenticatedPayrollSimulasiRoute
  AuthenticatedPayrollSlipGajiRoute: typeof AuthenticatedPayrollSlipGajiRoute
  AuthenticatedProduksiMasterPekerjaanRoute: typeof AuthenticatedProduksiMasterPekerjaanRoute
  AuthenticatedProduksiRekapRoute: typeof AuthenticatedProduksiRekapRoute
  AuthenticatedProduksiTarifSiteRoute: typeof AuthenticatedProduksiTarifSiteRoute
  AuthenticatedProduksiTerminalSetoranRoute: typeof AuthenticatedProduksiTerminalSetoranRoute
  AuthenticatedProduksiTransaksiRoute: typeof AuthenticatedProduksiTransaksiRoute
  AuthenticatedKaryawanDataKaryawanEmployeeUidRoute: typeof AuthenticatedKaryawanDataKaryawanEmployeeUidRouteWithChildren
  AuthenticatedKaryawanUbahKaryawanEmployeeUidRoute: typeof AuthenticatedKaryawanUbahKaryawanEmployeeUidRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdministrasiAuditTrailRoute:
    AuthenticatedAdministrasiAuditTrailRoute,
  AuthenticatedAdministrasiMasterDataRoute:
    AuthenticatedAdministrasiMasterDataRoute,
  AuthenticatedAdministrasiPengaturanRoute:
    AuthenticatedAdministrasiPengaturanRoute,
  AuthenticatedAdministrasiTemplateDokumenRoute:
    AuthenticatedAdministrasiTemplateDokumenRoute,
  AuthenticatedAdministrasiUserHakAksesRoute:
    AuthenticatedAdministrasiUserHakAksesRoute,
  AuthenticatedAttendanceKoreksiRoute: AuthenticatedAttendanceKoreksiRoute,
  AuthenticatedAttendanceMasterShiftRoute:
    AuthenticatedAttendanceMasterShiftRoute,
  AuthenticatedAttendanceMonitoringHarianRoute:
    AuthenticatedAttendanceMonitoringHarianRoute,
  AuthenticatedAttendanceRekapRoute: AuthenticatedAttendanceRekapRoute,
  AuthenticatedAttendanceScanRoute: AuthenticatedAttendanceScanRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedKaryawanCetakIdCardRoute: AuthenticatedKaryawanCetakIdCardRoute,
  AuthenticatedKaryawanDataKaryawanRoute:
    AuthenticatedKaryawanDataKaryawanRouteWithChildren,
  AuthenticatedKaryawanDokumenRoute:
    AuthenticatedKaryawanDokumenRouteWithChildren,
  AuthenticatedKaryawanPkwtRoute: AuthenticatedKaryawanPkwtRouteWithChildren,
  AuthenticatedKaryawanPkwtDokumenRoute: AuthenticatedKaryawanPkwtDokumenRoute,
  AuthenticatedKaryawanRiwayatMutasiRoute:
    AuthenticatedKaryawanRiwayatMutasiRoute,
  AuthenticatedKaryawanTambahKaryawanRoute:
    AuthenticatedKaryawanTambahKaryawanRoute,
  AuthenticatedPayrollApprovalClosingRoute:
    AuthenticatedPayrollApprovalClosingRoute,
  AuthenticatedPayrollPeriodeRoute: AuthenticatedPayrollPeriodeRoute,
  AuthenticatedPayrollRiwayatRoute: AuthenticatedPayrollRiwayatRoute,
  AuthenticatedPayrollSimulasiRoute: AuthenticatedPayrollSimulasiRoute,
  AuthenticatedPayrollSlipGajiRoute: AuthenticatedPayrollSlipGajiRoute,
  AuthenticatedProduksiMasterPekerjaanRoute:
    AuthenticatedProduksiMasterPekerjaanRoute,
  AuthenticatedProduksiRekapRoute: AuthenticatedProduksiRekapRoute,
  AuthenticatedProduksiTarifSiteRoute: AuthenticatedProduksiTarifSiteRoute,
  AuthenticatedProduksiTerminalSetoranRoute:
    AuthenticatedProduksiTerminalSetoranRoute,
  AuthenticatedProduksiTransaksiRoute: AuthenticatedProduksiTransaksiRoute,
  AuthenticatedKaryawanDataKaryawanEmployeeUidRoute:
    AuthenticatedKaryawanDataKaryawanEmployeeUidRouteWithChildren,
  AuthenticatedKaryawanUbahKaryawanEmployeeUidRoute:
    AuthenticatedKaryawanUbahKaryawanEmployeeUidRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
